### ISSUE TITLE
About generating Networks

### ISSUE THREAD

**Issue by Azzaare** [JuliaGraphs/JuliaGraphs-meta#1]
Hi there,

I have to generate some Networks for a personal project, so why not include some of the algorithms I use in JuliaGraphs. So it is not in a rush.

I was just wondering where would be the best place to incorporate those networks generators. There is a generator part for unweighted/unlabelled graphs in `LightGraphs.jl`. There  is also the `Networks.jl` package, but it seems to be thin at the moment.

Any idea? Ha, and I join gitter, so I can discuss actively if needed.

**Comment by sbromberger** [comment]
@Azzaare - you might also consider LightGraphsExtras, specifically in the https://github.com/JuliaGraphs/LightGraphsExtras.jl/tree/master/src/datasets directory.
