### ISSUE TITLE
Organization standards

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/JuliaGraphs-meta#3]
I wanted to get discussion going on some organization-wide standards. To help explain, here are two that I think we should adopt:

Packages under JuliaGraphs should
1.  have CI and code coverage configured and should use both when determining suitability of pull requests for merging.
2.  use Documenter for any complex package, or static documentation files otherwise.
3.  use Base.Test as the testing framework.
4.  be registered with METADATA.jl when at an appropriate level of maturity.

What else?

**Comment by sbromberger** [comment]
cc @JuliaGraphs/graphplots @JuliaGraphs/lgcontributors @JuliaGraphs/nlcore - just to make you aware that this issues list exists.

**Comment by sbromberger** [comment]
5. Attobot should be enabled for release tagging.

**Comment by gdalle** [comment]
Closing this since Julia good practices have evolved, but we're gonna get new discussions going
