### ISSUE TITLE
Preparing for 0.6

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/JuliaGraphs-meta#6]
We need a concerted effort by all repo owners:
* @abhijithanilkumar (NetworkLayout)
* @afternone (GraphPlot)
* ~~@CarloLucibello (GraphVisualize)~~
* @sbromberger / @jpfairbanks (~~LightGraphs~~, LightGraphsExtras)

to make sure all errors & deprecation warnings are fixed in Julia 0.6 by the time it's released.

Please use this issue to document status / progress.

**Comment by sbromberger** [comment]
For LightGraphs:

`sbromberger/simplegraphs` is passing all tests under 0.6 and will be the first release to drop support for 0.5.

**Comment by CarloLucibello** [comment]
GraphVisualize didn't ever leave early development stage and never achieved real usabilty. As a consequence it wasn't even registered. In the near future I'm planning to rebase the project on Erdos, now that it supports abstract graphs and graphs with edge/vertex properties (soon to come). I'd like to use that repo for the rebase, but if you want to reserve it for LightGraphs, or if there is some kind of policy that the JuliaGraphs org should be LG centered I can start a new repo somewhere else

**Comment by sbromberger** [comment]
@CarloLucibello why don't I just transfer the repo to you, since you're the only contributor? Then you can do what you need to with it.

**Comment by CarloLucibello** [comment]
ok, thanks!

**Comment by sbromberger** [comment]
It should be yours at this point....

**Comment by sbromberger** [comment]
@afternone - looks like GraphPlot is failing because of Compose.jl... so I guess we wait.

**Comment by abhijithanilkumar** [comment]
For NetworkLayout : 
[This](https://github.com/JuliaGraphs/NetworkLayout.jl/pull/14) PR is passing the tests and will be the first release to support 0.6.

**Comment by sbromberger** [comment]
Closing out since we're well past 0.6-release.
